import Head from 'next/head';
import { putAuthPassword } from '@/api/auth';

export default function Home() {
  const handleClick = async () => {
    try {
      const res = await putAuthPassword({
        password: 'oldpassword123',
        newPassword: 'newpassword123',
      });
      console.log(res);
    } catch (error) {
      // HTTP 전송 오류 처리
      console.error(error);
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main>123123123123</main>
        <button onClick={handleClick}>테스트 실행</button>
      </div>
    </>
  );
}
