import Head from 'next/head';
import { postAuthLogin } from '@/api/auth';
import { postDashboards } from '@/api/dashboards';

export default function Home() {
  const handleLogin = async () => {
    try {
      const res = await postAuthLogin({
        email: 'user@example.com',
        password: 'password123',
      });
      console.log(res);
    } catch (error) {
      // HTTP 전송 오류 처리
      console.error(error);
    }
  };

  const handleCreate = async () => {
    try {
      const res = await postDashboards({
        title: 'New Dashboard',
        color: '#FF5733',
      });
      console.log(res);
    } catch (error) {
      // HTTP 전송 오류 처리
      console.error(error);
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main>123123123123</main>
        <button onClick={handleLogin}>로그인</button>
        <button onClick={handleCreate}>대시보드 생성</button>
      </div>
    </>
  );
}
